# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation
---
# APPLY_FIXES: all
ENABLE:
  - ENV
  - HTML
  - JSON
  - MARKDOWN
  - YAML
  - ACTION
  - REPOSITORY
DISABLE_LINTERS:
  - JSON_JSONLINT
  - JSON_ESLINT_PLUGIN_JSONC
  - REPOSITORY_CHECKOV
  - REPOSITORY_GRYPE
  - REPOSITORY_TRIVY
  - REPOSITORY_KICS
  - REPOSITORY_DEVSKIM

EXCLUDED_DIRECTORIES: ['node_modules', 'megalinter-reports', 'dist', 'build', 'public', 'private', 'generated']
FILTER_REGEX_EXCLUDE: '(pnpm-lock.yaml|pnpm-workspace.yaml)'

# GRAPHQL_SCHEMA_LINTER_ARGUMENTS: '--config graphql.config.ts'
HTML_FILTER_REGEX_EXCLUDE: '(cypress/|nodemailer/templates/|bundle-stats.html)'
JSON_PRETTIER_CONFIG_FILE: 'packages/prettier-config/prettier.config.js'
REPOSITORY_SECRETLINT_ARGUMENTS: '--secretlintrc packages/megalinter-config/.secretlintrc.js'
REPOSITORY_TRUFFLEHOG_ARGUMENTS: '--exclude-paths=(^|/)node_modules(/|$)'

EMAIL_REPORTER: false
FILEIO_REPORTER: false
FLAVOR_SUGGESTIONS: false
GITHUB_STATUS_REPORTER: false
JSON_REPORTER: true
PRINT_ALL_FILES: false
SHOW_ELAPSED_TIME: true
