# eslint-disable unicorn/filename-case
# eslint-disable yml/plain-scalar
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation
---
# APPLY_FIXES: all
ENABLE:
  - ACTION
  - BASH
  - CSS
  - DOCKERFILE
  - EDITORCONFIG
  - ENV
  - HTML
  - JAVASCRIPT
  - JSON
  - MARKDOWN
  - REPOSITORY
  - TSX
  - TYPESCRIPT
  - YAML
DISABLE_LINTERS:
  - JAVASCRIPT_STANDARD
  - TYPESCRIPT_STANDARD
  - CSS_SCSS_LINT
  - REPOSITORY_GRYPE
  - REPOSITORY_TRIVY
  - REPOSITORY_TRIVY_SBOM

EXCLUDED_DIRECTORIES:
  ['.git', 'node_modules', 'megalinter-reports', 'dist', 'build', 'public', 'private', 'generated', 'meta']
FILTER_REGEX_EXCLUDE: '(pnpm-lock.yaml|pnpm-workspace.yaml)'
HTML_FILTER_REGEX_EXCLUDE: '(cypress/|nodemailer/templates/|bundle-stats.html)'
JSON_FILTER_REGEX_EXCLUDE: '/migrations/meta/'

BASH_SHELLCHECK_ARGUMENTS: '-S warning'
BASH_SHFMT_ARGUMENTS: '--case-indent --indent 2 --space-redirects --language-dialect bash'

CSS_STYLELINT_ARGUMENTS: '--config-basedir=./node_modules'
CSS_STYLELINT_CLI_EXECUTABLE: ['node_modules/.bin/stylelint']
CSS_STYLELINT_CONFIG_FILE: 'stylelint.config.js'

EDITORCONFIG_EDITORCONFIG_CHECKER_CONFIG_FILE: 'packages/megalinter-config/.editorconfig-checker.json'
# GRAPHQL_SCHEMA_LINTER_ARGUMENTS: '--config graphql.config.ts'

HTML_DJLINT_FILTER_REGEX_EXCLUDE: '(?i)emailtemplate.*\.html$'

JAVASCRIPT_DEFAULT_STYLE: 'prettier'
JAVASCRIPT_ES_CLI_EXECUTABLE: ['node_modules/.bin/eslint']
JAVASCRIPT_ES_COMMAND_REMOVE_ARGUMENTS:
  - --no-eslintrc
  - -c
  - /github/workspace/eslint.config.js
  - --no-ignore
JAVASCRIPT_PRETTIER_CONFIG_FILE: 'packages/prettier-config/prettier.config.js'
JAVASCRIPT_ES_CONFIG_FILE: 'eslint.config.js'

JSON_JSONLINT_ARGUMENTS: '--comments'
JSON_PRETTIER_CONFIG_FILE: 'packages/prettier-config/prettier.config.js'

REPOSITORY_CHECKOV_CONFIG_FILE: 'packages/megalinter-config/.checkov.yml'
REPOSITORY_DEVSKIM_CONFIG_FILE: 'packages/megalinter-config/.devskim.json'
REPOSITORY_KICS_ARGUMENTS: '--disable-full-descriptions'
REPOSITORY_SECRETLINT_CONFIG_FILE: 'packages/megalinter-config/.secretlintrc.js'
REPOSITORY_TRUFFLEHOG_ARGUMENTS: '--exclude-paths=packages/megalinter-config/trufflehog_exclude.txt'

TSX_ES_CLI_EXECUTABLE: ['node_modules/.bin/eslint']
TSX_ES_COMMAND_REMOVE_ARGUMENTS:
  - --no-eslintrc
  - -c
  - /github/workspace/eslint.config.js
  - --no-ignore
TSX_PRETTIER_CONFIG_FILE: 'packages/prettier-config/prettier.config.js'
TSX_ES_CONFIG_FILE: 'eslint.config.js'

TYPESCRIPT_DEFAULT_STYLE: 'prettier'
TYPESCRIPT_ES_CLI_EXECUTABLE: ['node_modules/.bin/eslint']
TYPESCRIPT_ES_COMMAND_REMOVE_ARGUMENTS:
  - --no-eslintrc
  - -c
  - /github/workspace/eslint.config.js
  - --no-ignore
TYPESCRIPT_PRETTIER_CONFIG_FILE: 'packages/prettier-config/prettier.config.js'
TYPESCRIPT_ES_CONFIG_FILE: 'eslint.config.js'

EMAIL_REPORTER: false
FILEIO_REPORTER: false
FLAVOR_SUGGESTIONS: false
GITHUB_STATUS_REPORTER: false
JSON_REPORTER: true
PRINT_ALL_FILES: false
SHOW_ELAPSED_TIME: true
UPDATED_SOURCES_REPORTER: false
