# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation
---
# APPLY_FIXES: all
ENABLE:
  - ENV
  - HTML
  - JSON
  - MARKDOWN
  - YAML
  - ACTION
  - REPOSITORY
DISABLE_LINTERS:
  - REPOSITORY_GRYPE
  - REPOSITORY_TRIVY
  - REPOSITORY_TRIVY_SBOM

EXCLUDED_DIRECTORIES: ['node_modules', 'megalinter-reports', 'dist', 'build', 'public', 'private', 'generated']
FILTER_REGEX_EXCLUDE: '(pnpm-lock.yaml|pnpm-workspace.yaml)'
HTML_FILTER_REGEX_EXCLUDE: '(cypress/|nodemailer/templates/|bundle-stats.html)'
JSON_FILTER_REGEX_EXCLUDE: '/migrations/meta/'

# GRAPHQL_SCHEMA_LINTER_ARGUMENTS: '--config graphql.config.ts'
JSON_PRETTIER_CONFIG_FILE: 'packages/prettier-config/prettier.config.js'
REPOSITORY_CHECKOV_CONFIG_FILE: 'packages/megalinter-config/.checkov.yml'
REPOSITORY_DEVSKIM_CONFIG_FILE: 'packages/megalinter-config/.devskim.json'
REPOSITORY_KICS_ARGUMENTS: '--disable-full-descriptions'
REPOSITORY_SECRETLINT_CONFIG_FILE: 'packages/megalinter-config/.secretlintrc.js'
REPOSITORY_TRUFFLEHOG_ARGUMENTS: '--exclude-paths=packages/megalinter-config/trufflehog_exclude.txt'

EMAIL_REPORTER: false
FILEIO_REPORTER: false
FLAVOR_SUGGESTIONS: false
GITHUB_STATUS_REPORTER: false
JSON_REPORTER: true
PRINT_ALL_FILES: false
SHOW_ELAPSED_TIME: true
