packages:
  - packages/**

injectWorkspacePackages: true

minimumReleaseAge: 7200

minimumReleaseAgeExclude:
  - '@types/*'
  - '@secretlint/*'
  - secretlint

onlyBuiltDependencies:
  - secp256k1
  - unrs-resolver
