packages:
  - apps/**
  - packages/**

injectWorkspacePackages: true

onlyBuiltDependencies:
  - argon2
  - core-js
  - cypress
  - esbuild
  - msw
  - sharp
  - unrs-resolver
  - '@apollo/protobufjs'
  - bcrypt
  - secp256k1
