packages:
  - apps/**
  - packages/**

allowBuilds:
  '@apollo/protobufjs': true
  '@parcel/watcher': true
  '@swc/core': true
  argon2: true
  bcrypt: true
  core-js: true
  core-js-pure: true
  cypress: true
  esbuild: true
  msw: true
  secp256k1: true
  sharp: true
  unrs-resolver: true
gitBranchLockfile: true

injectWorkspacePackages: true
mergeGitBranchLockfilesBranchPattern:
  - main
minimumReleaseAge: 7200
minimumReleaseAgeExclude:
  - '@types/*'
  - '@secretlint/*'
  - 'secretlint'
overrides:
  browserslist: ^4.28.0
