{
 "title": "Techexpo-CRM",
 "tags": [
  "docker",
  "expressjs",
  "redis",
  "mongo",
  "postgres"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nodejs_instance",
    "label": "nodejs_instance",
    "query": {
     "query": "label_values(express_nodejs_version_info,instance)"
    }
   },
   {
    "name": "mongo_instance",
    "label": "mongo_instance",
    "query": {
     "query": "label_values(mongodb_up,instance)"
    }
   },
   { "name": "postgres_instance", "label": "postgres_instance", "query": { "query": "label_values(pg_up,instance)" } },
   {
    "name": "redis_instance",
    "label": "redis_instance",
    "query": {
     "query": "label_values(redis_up,instance)"
    }
   },
   {
    "name": "mailpit_instance",
    "label": "mailpit_instance",
    "query": {
     "query": "label_values(mailpit_uptime_seconds,instance)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Services Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prometheus_ready", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(up{instance=\"$nodejs_instance\"}[1m]) == 1\r\nand on(job) min_over_time(express_up{instance=\"$nodejs_instance\"}[1m]) == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mongo Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(up{instance=\"$mongo_instance\"}[1m]) == 1\r\nand ignoring(cluster_role) min_over_time(mongodb_up{instance=\"$mongo_instance\"}[1m]) == 1\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(up{instance=\"$postgres_instance\"}[1m]) == 1\r\nand on(job) min_over_time(pg_up{instance=\"$postgres_instance\"}[1m]) == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(up{instance=\"$redis_instance\"}[1m]) == 1\r\nand on(job) min_over_time(redis_up{instance=\"$redis_instance\"}[1m]) == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mailpit Status (DEV)",
   "type": "stat",
   "description": "Mailpit - Development use only",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(mailpit_uptime_seconds{job=\"mailpit\", instance=\"$mailpit_instance\"}[1m]) > bool 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Exporter Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$nodejs_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mongo Exporter Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$mongo_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres Exporter Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$postgres_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Exporter Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$redis_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mailpit Exporter Status (DEV)",
   "type": "stat",
   "description": "Mailpit - Development use only",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$mailpit_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mongo Latency Avg (s)",
   "type": "stat",
   "description": "The average latency of Mongo, per second",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  mongodb_ss_opWorkingTime_reads_latency{instance=\"$mongo_instance\"}\r\n+ mongodb_ss_opWorkingTime_writes_latency{instance=\"$mongo_instance\"}\r\n+ mongodb_ss_opWorkingTime_commands_latency{instance=\"$mongo_instance\"}\r\n+ mongodb_ss_opWorkingTime_transactions_latency{instance=\"$mongo_instance\"}\r\n)\r\n/\r\n(\r\n  mongodb_ss_opWorkingTime_reads_ops{instance=\"$mongo_instance\"}\r\n+ mongodb_ss_opWorkingTime_writes_ops{instance=\"$mongo_instance\"}\r\n+ mongodb_ss_opWorkingTime_commands_ops{instance=\"$mongo_instance\"}\r\n+ mongodb_ss_opWorkingTime_transactions_ops{instance=\"$mongo_instance\"}\r\n) / 1000\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres Latency Avg (s)",
   "type": "stat",
   "description": "The average latency of Postgres, per second",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(rate(pg_stat_database_blks_read{datname=\"CRM-Server\", instance=\"$postgres_instance\"}[$interval]), \"service\", \"$1\", \"instance\", \"(.*)\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Latency Avg (s)",
   "type": "stat",
   "description": "The combined latency of all cmds in Redis, per second",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n  sum by (instance) (rate(redis_commands_duration_seconds_total[$interval]))\r\n  /\r\n  sum by (instance) (rate(redis_commands_total[$interval])),\r\n  \"service\", \"$1\", \"instance\", \"(.*)\"\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Docker Containers - cAdvisor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node list",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 469 },
     "targets": [
      {
       "expr": "count(container_last_seen{image!=\"\"}) by (instance, name)"
      },
      {
       "expr": "sum(machine_cpu_cores) by (instance, name)"
      },
      {
       "expr": "sum by (name, instance) (irate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100) * on(instance) group_left() (sum by (instance) (1 / machine_cpu_cores))"
      },
      {
       "expr": "sum by (name, instance) (container_memory_usage_bytes{image!=\"\"} - container_memory_cache{image!=\"\"}) / scalar(sum by (instance) (machine_memory_bytes)) * 100"
      },
      {
       "expr": "sum(container_memory_usage_bytes{image!=\"\"}) by (instance, name) - sum(container_memory_cache{image!=\"\"}) by (instance, name)"
      },
      {
       "expr": "sum(machine_memory_bytes) by (instance, name)"
      },
      {
       "expr": "sum by (instance, name) (irate(container_fs_reads_bytes_total[10m]))"
      },
      {
       "expr": "sum by (instance, name) (irate(container_fs_writes_bytes_total[5m]))"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{image!=\"\"}[5m])) by (instance, name)"
      },
      {
       "expr": "sum(irate(container_network_receive_bytes_total{image!=\"\"}[5m])) by (instance, name)"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 476 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum without (dc,from,id) (irate(container_cpu_user_seconds_total{image!=\"\"}[$interval]) * 100)",
       "legendFormat": "{{name}}: {{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 483 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum without (dc,from,id) (container_memory_usage_bytes{image!=\"\"} - container_memory_cache{image!=\"\"})",
       "legendFormat": "{{name}}: {{instance}}"
      }
     ]
    },
    {
     "title": "Network Tx:sum",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 490 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum without (dc,from,id) (irate(container_network_transmit_bytes_total{image!=\"\"}[$interval]))",
       "legendFormat": "{{name}}: {{instance}}"
      }
     ]
    },
    {
     "title": "Network Rx:sum",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 490 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum without (dc,from,id) (irate(container_network_receive_bytes_total{image!=\"\"}[$interval]))",
       "legendFormat": "{{name}}: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API - ExpressJS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Countby by Route",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (route) (\r\n  rate(express_http_request_duration_seconds_count{instance=\"$nodejs_instance\"}[1m])\r\n)",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Request Count by Code",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (code) (\r\n  rate(express_http_request_duration_seconds_count{instance=\"$nodejs_instance\"}[1m])\r\n)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Request Duration by Code",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(express_http_request_duration_seconds_count{instance=\"$nodejs_instance\"}[$interval])) by (code)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Response Latency",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(express_http_request_duration_seconds_bucket{instance=\"$nodejs_instance\"}[$interval])) by (status,le))",
       "legendFormat": "{{status}} (95%)"
      },
      {
       "expr": "histogram_quantile(1, sum(rate(http_request_duration_seconds_bucket{instance=\"$nodejs_instance\"}[$interval])) by (status,le))",
       "legendFormat": "{{status}} (100%)"
      }
     ]
    },
    {
     "title": "Top 5 Request Count",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, sum by(route) (express_http_request_duration_seconds_count{instance=~\"$nodejs_instance\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 5 Request Duration",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(5, sum by (route)(express_http_request_duration_seconds_sum{instance=\"$nodejs_instance\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 5 Success Count",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, express_http_request_duration_seconds_count{instance=\"$nodejs_instance\",code=~\"[23]..\"})",
       "legendFormat": "{{status}}  {{route}}"
      }
     ]
    },
    {
     "title": "Top 5 Error Count",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5, express_http_request_duration_seconds_count{instance=\"$nodejs_instance\",code=~\"[45]..\"})",
       "legendFormat": "{{code}} {{route}}"
      }
     ]
    },
    {
     "title": "Rate of CPU Time Spent",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(express_process_cpu_seconds_total{instance=\"$nodejs_instance\"}[$interval])",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Process Memory",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "express_process_virtual_memory_bytes{instance=\"$nodejs_instance\"}",
       "legendFormat": "virtual memory"
      },
      {
       "expr": "express_process_heap_bytes{instance=~\"$nodejs_instance\"}",
       "legendFormat": "heap memory"
      }
     ]
    },
    {
     "title": "Event Loop Latency",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "express_nodejs_eventloop_lag_seconds{instance=\"$nodejs_instance\"}",
       "legendFormat": "last"
      },
      {
       "expr": "express_nodejs_eventloop_lag_p99_seconds{instance=~\"$nodejs_instance\"}",
       "legendFormat": "p99"
      },
      {
       "expr": "express_nodejs_eventloop_lag_p50_seconds{instance=~\"$nodejs_instance\"}",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "Active Handlers/Requests",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "express_nodejs_active_handles_total{instance=\"$nodejs_instance\"}",
       "legendFormat": "Active Handler"
      },
      {
       "expr": "express_nodejs_active_requests_total{instance=\"$nodejs_instance\"}",
       "legendFormat": "Active Request"
      }
     ]
    },
    {
     "title": "Heap Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "express_nodejs_heap_size_total_bytes{instance=\"$nodejs_instance\"}",
       "legendFormat": "total"
      },
      {
       "expr": "express_nodejs_heap_size_used_bytes{instance=\"$nodejs_instance\"}",
       "legendFormat": "used"
      },
      {
       "expr": "express_process_resident_memory_bytes{instance=\"$nodejs_instance\"}",
       "legendFormat": "resident"
      },
      {
       "expr": "express_nodejs_external_memory_bytes{instance=\"$nodejs_instance\"}",
       "legendFormat": "external"
      }
     ]
    },
    {
     "title": "Heap Space Used",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "express_nodejs_heap_space_size_used_bytes{instance=\"$nodejs_instance\"}",
       "legendFormat": "{{space}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DB: Postgres",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rows",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 20, "x": 0, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "fetched",
       "expr": "sum(irate(pg_stat_database_tup_fetched{datname=\"CRM-Server\",instance=\"$postgres_instance\"}[$interval]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "fetched",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "tup_fetched" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      },
      {
       "alias": "fetched",
       "expr": "sum(irate(pg_stat_database_tup_returned{datname=\"CRM-Server\",instance=\"$postgres_instance\"}[$interval]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "returned",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "tup_fetched" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      },
      {
       "alias": "fetched",
       "expr": "sum(irate(pg_stat_database_tup_inserted{datname=\"CRM-Server\",instance=\"$postgres_instance\"}[$interval]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "inserted",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "tup_fetched" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      },
      {
       "alias": "fetched",
       "expr": "sum(irate(pg_stat_database_tup_updated{datname=\"CRM-Server\",instance=\"$postgres_instance\"}[$interval]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "updated",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "tup_fetched" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      },
      {
       "alias": "fetched",
       "expr": "sum(irate(pg_stat_database_tup_deleted{datname=\"CRM-Server\",instance=\"$postgres_instance\"}[$interval]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "deleted",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "tup_fetched" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "QPS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(irate(pg_stat_database_xact_commit{datname=\"CRM-Server\",instance=\"$postgres_instance\"}[$interval])) + sum(irate(pg_stat_database_xact_rollback{datname=\"CRM-Server\",instance=\"$postgres_instance\"}[$interval]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "xact_commit" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "10s" ], "type": "non_negative_derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "Active connections",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "pg_stat_database_numbackends{datname=\"CRM-Server\",instance=\"$postgres_instance\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Change Stats",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(pg_stat_database_tup_inserted{instance=\"$postgres_instance\", datname=\"CRM-Server\"}[$interval])",
       "legendFormat": "INSERT"
      },
      {
       "expr": "irate(pg_stat_database_tup_updated{instance=\"$postgres_instance\", datname=\"CRM-Server\"}[$interval])",
       "legendFormat": "UPDATE"
      },
      {
       "expr": "irate(pg_stat_database_tup_deleted{instance=\"$postgres_instance\", datname=\"CRM-Server\"}[$interval])",
       "legendFormat": "DELETE"
      }
     ]
    },
    {
     "title": "Conflicts/Deadlocks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 165 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "conflicts",
       "expr": "sum(rate(pg_stat_database_deadlocks{datname=\"CRM-Server\",instance=\"$postgres_instance\"}[$interval]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "deadlocks",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "conflicts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      },
      {
       "alias": "deadlocks",
       "expr": "sum(rate(pg_stat_database_conflicts{datname=\"CRM-Server\",instance=\"$postgres_instance\"}[$interval]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "conflicts",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "deadlocks" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 172 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "Buffers Allocated",
       "expr": "irate(pg_stat_bgwriter_buffers_alloc_total{instance=\"$postgres_instance\"}[$interval])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "buffers_alloc",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "buffers_alloc" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      },
      {
       "alias": "Buffers Allocated",
       "expr": "irate(pg_stat_bgwriter_buffers_clean_total{instance=\"$postgres_instance\"}[$interval])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "buffers_clean",
       "measurement": "postgresql",
       "select": [
        [
         { "params": [ "buffers_alloc" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         {
          "params": [],
          "type": "difference"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$instance$/" }
       ]
      }
     ]
    },
    {
     "title": "Cache hit ratio",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 172 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(pg_stat_database_blks_hit{datname=\"CRM-Server\",instance=\"$postgres_instance\"}) / (sum(pg_stat_database_blks_hit{datname=\"CRM-Server\",instance=\"$postgres_instance\"}) + sum(pg_stat_database_blks_read{datname=\"CRM-Server\",instance=\"$postgres_instance\"}))",
       "legendFormat": "cache hit rate"
      }
     ]
    }
   ]
  },
  {
   "title": "DB: Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Commands per second",
     "type": "timeseries",
     "description": "Average taken across instances",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(irate(redis_commands_total{instance=\"$redis_instance\"}[$interval])) by (cmd)",
       "legendFormat": "{{cmd}}"
      }
     ]
    },
    {
     "title": "Command latency per second",
     "type": "timeseries",
     "description": "Average taken across instances",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(irate(redis_commands_duration_seconds_total{instance=\"$redis_instance\"}[$interval])) by (cmd)\n  /\navg(irate(redis_commands_total{instance=\"$redis_instance\"}[$interval])) by (cmd)\n",
       "legendFormat": "{{ cmd }}"
      }
     ]
    },
    {
     "title": "Response time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(redis_commands_duration_seconds_total{instance=\"$redis_instance\"}[$interval])) / sum(rate(redis_commands_processed_total{instance=\"$redis_instance\"}[$interval]))",
       "legendFormat": "Response Time"
      }
     ]
    },
    {
     "title": "Total Items per DB",
     "type": "timeseries",
     "description": "Sum taken across instances",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum (redis_db_keys{instance=\"$redis_instance\"}) by (db)",
       "legendFormat": "{{ db }}"
      }
     ]
    },
    {
     "title": "Expiring vs Not-Expiring Keys",
     "type": "timeseries",
     "description": "Sum taken across instances",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum (redis_db_keys{instance=\"$redis_instance\"}) - sum (redis_db_keys_expiring{instance=\"$redis_instance\"})",
       "legendFormat": "Not expiring"
      },
      {
       "expr": "sum(redis_db_keys_expiring{instance=\"$redis_instance\"})",
       "legendFormat": "Expiring"
      }
     ]
    },
    {
     "title": "Key evictions per second per instance",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(redis_evicted_keys_total{instance=\"$redis_instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Connected/Blocked Clients",
     "type": "timeseries",
     "description": "Sum taken across instances",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(redis_connected_clients{instance=\"$redis_instance\"})",
       "legendFormat": "Connected"
      },
      {
       "expr": "sum(redis_blocked_clients{instance=~\"$instance\"})",
       "legendFormat": "Blocked"
      }
     ]
    },
    {
     "title": "Connections usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "redis_connected_clients{instance=\"$redis_instance\"}",
       "legendFormat": "Clients"
      },
      {
       "expr": "redis_config_maxclients{instance=\"$redis_instance\"}",
       "legendFormat": "Max Clients"
      }
     ]
    },
    {
     "title": "Connected slaves by instance",
     "type": "timeseries",
     "description": "This metric will only be non-zero if the instance is a master",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(redis_connected_slaves{instance=\"$redis_instance\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total Memory Usage",
     "type": "timeseries",
     "description": "Total taken across instances",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(redis_memory_used_bytes{instance=\"$redis_instance\"})",
       "legendFormat": "Used Memory"
      },
      {
       "expr": "sum(redis_memory_max_bytes{instance=~\"$redis_instance\"})",
       "legendFormat": "Configured max memory"
      },
      {
       "expr": "sum(redis_memory_used_rss_bytes{instance=~\"$redis_instance\"})",
       "legendFormat": "Used RSS memory"
      }
     ]
    },
    {
     "title": "Network Throughput",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(redis_net_input_bytes_total{instance=\"$redis_instance\"}[$interval])",
       "legendFormat": "Inbound"
      },
      {
       "expr": "rate(redis_net_output_bytes_total{instance=\"$redis_instance\"}[$interval])",
       "legendFormat": "Outbound"
      }
     ]
    },
    {
     "title": "Hit ratio per instance",
     "type": "timeseries",
     "description": "Hit rate shows the percentage of key space lookups that hit a key.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(irate(redis_keyspace_hits_total{instance=\"$redis_instance\"}[$interval]) / (irate(redis_keyspace_misses_total{instance=\"$redis_instance\"}[$interval]) + irate(redis_keyspace_hits_total{instance=\"$redis_instance\"}[$interval]))) by (instance)",
       "legendFormat": "{{instance}}"
      },
      { "expr": "1", "legendFormat": "Target hit ratio for cache" }
     ]
    }
   ]
  },
  {
   "title": "DB: Mongo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "UP Status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 107 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mongodb_up{instance=\"$mongo_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Mongodb Uptime",
     "type": "stat",
     "description": "Mongodb Service Uptime in hours",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mongodb_ss_uptime{instance=\"$mongo_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Current Connections",
     "type": "stat",
     "description": "The number of incoming connections from clients to the database server. This number includes the current shell session. Consider the value of connections.available to add more context to this datum.",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 107 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mongodb_ss_connections{conn_type=\"current\", instance=\"$mongo_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total Created Connections",
     "type": "stat",
     "description": "Count of all incoming connections created to the server. This number includes connections that have since closed.",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 107 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mongodb_ss_connections{conn_type=\"totalCreated\", instance=\"$mongo_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Available Connections",
     "type": "stat",
     "description": "The number of unused incoming connections available. Consider this value in combination with the value of connections.current to understand the connection load on the database, and the UNIX ulimit Settings document for more information about system thresholds on available connections.",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 107 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mongodb_ss_connections{conn_type=\"available\", instance=\"$mongo_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "stat",
     "description": "The number of active client connections to the server. Active client connections refers to client connections that currently have operations in progress.",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 107 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mongodb_ss_connections{conn_type=\"active\", instance=\"$mongo_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Document Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(mongodb_ss_metrics_document[$interval])",
       "legendFormat": "{{doc_op_type}}"
      }
     ]
    },
    {
     "title": "Query Operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(mongodb_ss_opcounters{instance=\"$mongo_instance\"}[$interval])",
       "legendFormat": "{{legacy_op_type}}"
      }
     ]
    },
    {
     "title": "Total Collections/DB",
     "type": "state-timeline",
     "description": "Number of collections in the database.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 118 },
     "targets": [
      {
       "expr": "mongodb_dbstats_collections{instance=\"$mongo_instance\"}",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Total Indexs/DB",
     "type": "state-timeline",
     "description": "Total number of indexes across all collections in the database.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 118 },
     "targets": [
      {
       "expr": "mongodb_dbstats_indexes{instance=\"$mongo_instance\"}",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Total Views/DB",
     "type": "state-timeline",
     "description": "Number of views in the database.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 118 },
     "targets": [
      {
       "expr": "mongodb_dbstats_views{instance=\"$mongo_instance\"}",
       "legendFormat": "{{database}}"
      }
     ]
    },
    {
     "title": "Allocated Storage to Collections in DB",
     "type": "timeseries",
     "description": "Sum of the space allocated to all collections in the database for document storage, including free space.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "mongodb_dbstats_storageSize{instance=\"$mongo_instance\"}",
       "legendFormat": "{{database}} "
      }
     ]
    },
    {
     "title": "Allocated Storage to Indexs in DB",
     "type": "timeseries",
     "description": "Sum of the space allocated to all indexes in the database, including free index space.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "mongodb_dbstats_indexSize{instance=\"$mongo_instance\"}",
       "legendFormat": "{{database}}"
      }
     ]
    }
   ]
  }
 ]
}