name: "tech-expo crm"
version: "3.7"
services:

  # Backend: NodeJS Express
  node-api:
    build:
      context: ../server

  # Frontend: React
  react-app:
    build:
      context: ../client
    profiles: [ "prod" ]
