export interface IProps {
  svgClass?: string;
  mirror?: boolean;
}
export type IIcon = ({ svgClass }: IProps) => JSX.Element;

export { default as IconAdministration } from './IconAdministration';
export { default as IconAudit } from './IconAudit';
export { default as IconArrowDownAlt } from './IconArrowDownAlt';
export { default as IconArrowDownDoubleAlt } from './IconArrowDownDoubleAlt';
export { default as IconArrowLeftAlt } from './IconArrowLeftAlt';
export { default as IconArrowLeftDoubleAlt } from './IconArrowLeftDoubleAlt';
export { default as IconArrowRightUp } from './IconArrowRightUp';
export { default as IconBillQuote } from './IconBillQuote';
export { default as IconCalendar } from './IconCalendar';
export { default as IconClose } from './IconClose';
export { default as IconCompanies } from './IconCompanies';
export { default as IconContacts } from './IconContacts';
export { default as IconCurrencyPound } from './IconCurrencyPound';
export { default as IconDashboard } from './IconDashboard';
export { default as IconDelete } from './IconDelete';
export { default as IconEdit } from './IconEdit';
export { default as IconEmail } from './IconEmail';
export { default as IconEye } from './IconEye';
export { default as IconInfoCircle } from './IconInfoCircle';
export { default as IconKanban } from './IconKanban';
export { default as IconLogout } from './IconLogout';
export { default as IconNotificationBell } from './IconNotificationBell';
export { default as IconNotebook } from './IconNotebook';
export { default as IconOperatorMinus } from './IconOperatorMinus';
export { default as IconOperatorPercent } from './IconOperatorPercent';
export { default as IconOperatorPlus } from './IconOperatorPlus';
export { default as IconPassword } from './IconPassword';
export { default as IconPhone } from './IconPhone';
export { default as IconPipe } from './IconPipe';
export { default as IconScrum } from './IconScrum';
export { default as IconSearch } from './IconSearch';
export { default as IconSettings } from './IconSettings';
export { default as IconSmartphone } from './IconSmartphone';
export { default as IconTheme } from './IconTheme';
export { default as IconTimezone } from './IconTimezone';
export { default as IconUser } from './IconUser';
export { default as IconUserTitle } from './IconUserTitle';
