/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as QuotesIndexRouteImport } from './routes/quotes/index'
import { Route as PipelineIndexRouteImport } from './routes/pipeline/index'
import { Route as KanbanIndexRouteImport } from './routes/kanban/index'
import { Route as ContactsIndexRouteImport } from './routes/contacts/index'
import { Route as CompaniesIndexRouteImport } from './routes/companies/index'
import { Route as CalendarIndexRouteImport } from './routes/calendar/index'
import { Route as AuditLogIndexRouteImport } from './routes/audit-log/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesIndexRoute = QuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineIndexRoute = PipelineIndexRouteImport.update({
  id: '/pipeline/',
  path: '/pipeline/',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanIndexRoute = KanbanIndexRouteImport.update({
  id: '/kanban/',
  path: '/kanban/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogIndexRoute = AuditLogIndexRouteImport.update({
  id: '/audit-log/',
  path: '/audit-log/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-log/': typeof AuditLogIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/kanban/': typeof KanbanIndexRoute
  '/pipeline/': typeof PipelineIndexRoute
  '/quotes/': typeof QuotesIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogIndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/companies': typeof CompaniesIndexRoute
  '/contacts': typeof ContactsIndexRoute
  '/kanban': typeof KanbanIndexRoute
  '/pipeline': typeof PipelineIndexRoute
  '/quotes': typeof QuotesIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-log/': typeof AuditLogIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/contacts/': typeof ContactsIndexRoute
  '/kanban/': typeof KanbanIndexRoute
  '/pipeline/': typeof PipelineIndexRoute
  '/quotes/': typeof QuotesIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-log/'
    | '/calendar/'
    | '/companies/'
    | '/contacts/'
    | '/kanban/'
    | '/pipeline/'
    | '/quotes/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-log'
    | '/calendar'
    | '/companies'
    | '/contacts'
    | '/kanban'
    | '/pipeline'
    | '/quotes'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/audit-log/'
    | '/calendar/'
    | '/companies/'
    | '/contacts/'
    | '/kanban/'
    | '/pipeline/'
    | '/quotes/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLogIndexRoute: typeof AuditLogIndexRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  KanbanIndexRoute: typeof KanbanIndexRoute
  PipelineIndexRoute: typeof PipelineIndexRoute
  QuotesIndexRoute: typeof QuotesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/': {
      id: '/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof QuotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline/': {
      id: '/pipeline/'
      path: '/pipeline'
      fullPath: '/pipeline/'
      preLoaderRoute: typeof PipelineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban/': {
      id: '/kanban/'
      path: '/kanban'
      fullPath: '/kanban/'
      preLoaderRoute: typeof KanbanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log/': {
      id: '/audit-log/'
      path: '/audit-log'
      fullPath: '/audit-log/'
      preLoaderRoute: typeof AuditLogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLogIndexRoute: AuditLogIndexRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  KanbanIndexRoute: KanbanIndexRoute,
  PipelineIndexRoute: PipelineIndexRoute,
  QuotesIndexRoute: QuotesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
