# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Cypress
permissions:
  contents: read

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
    paths:
      - 'apps/crm/client/cypress/**'

  push:
    branches: [main]
    paths:
      - 'apps/crm/client/cypress/**'

  workflow_dispatch: {}

jobs:
  cypress:
    runs-on: ubuntu-latest
    environment: testing
    env:
      NODE_ENV: test

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup PNPM
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          run_install: false

      - name: Setup Node 22.18.0
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22.23.1
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Cache Cypress Binary
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: cypress-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install

      - name: Ensure Cypress binary
        run: pnpm --filter @apps/crm-client exec cypress install

      - name: Build @apps/crm-shared types
        run: pnpm --filter @apps/crm-shared build

      - name: CRM Client - Cypress Testing
        run: pnpm --filter @apps/crm-client cypress:e2e

        #
# https://github.com/cypress-io/github-action/issues/1590
# NOTE: Bug with cypress-action; relies on npx to source binary cache;
# 'working-directory' requires lock-file presence (not in current monorepo setup);
# 'working-directory' required for the installation step
# - name: CRM Client - Cypress Binary
#   uses: cypress-io/github-action@v6
#   with:
#     working-directory: ./
#     project: apps/crm/client
#     install: true
#     runTests: false
# env:
#   CYPRESS_CACHE_FOLDER: ~/.cache/Cypress
# - name: CRM Client - Cypress Testing
#   uses: cypress-io/github-action@v6
#   with:
#     working-directory: apps/crm/client
#     command: pnpm run cypress:e2e
#     install: false
#     component: false
#     record: false
#     publish-summary: true
# env:
#   CYPRESS_CACHE_FOLDER: ~/.cache/Cypress
