# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Playwright
permissions: read-all

on:
  pull_request:
    branches: [main]
    paths:
      - 'apps/crm/client/e2e/**'

  push:
    branches: [main]
    paths:
      - 'apps/crm/client/e2e/**'

  workflow_dispatch: {}

jobs:
  playwright:
    runs-on: ubuntu-latest
    environment: testing

    permissions:
      contents: read
      packages: read
      statuses: write

    container:
      image: mcr.microsoft.com/playwright:v1.59.1-noble

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PNPM
        uses: pnpm/action-setup@v5
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Build shared
        run: pnpm --filter @apps/crm-shared build

      - name: Build graphql codegen
        run: pnpm --filter @apps/crm-client codegen

      - name: Run Playwright tests
        run: pnpm --filter @apps/crm-client playwright:test
        env:
          DOTENV_PRIVATE_KEY_CI_CLIENT: ${{ secrets.DOTENV_PRIVATE_KEY_CI_CLIENT }}

      - name: Playwright Artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v7
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 5
