# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Renovate
permissions:
  contents: write
  pull-requests: write

on: # yamllint disable-line rule:truthy
  schedule:
    # minute (0-59) - hour (0-23) - date (1-31) - month (1-12 or JAN-DEC) - day (0-6 or SUN-SAT)
    - cron: '0 09 * * SUN'
  workflow_dispatch: {}

jobs:
  dependencies:
    name: dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Renovate
        uses: renovatebot/github-action@3064367f740a1a91cca218698a63902689cce200 # v46.1.20
        with:
          configurationFile: .github/renovate.jsonc
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_PLATFORM: github
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: ${{ vars.RENOVATE_DEBUG == 'true' && 'debug' || 'info' }}
          LOG_FILE: renovate.log

      - name: Renovate Artifacts
        if: success() || failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Renovate report
          path: renovate.log
          retention-days: 1
