# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Vitest
permissions:
  contents: read

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
    paths:
      - 'apps/crm/client/**/*.test.*'
      - 'apps/crm/client/**/*.spec.*'
      - 'apps/crm/server/**/*.test.*'
      - 'apps/crm/server/**/*.spec.*'

  push:
    branches: [main]
    paths:
      - 'apps/crm/client/**/*.test.*'
      - 'apps/crm/client/**/*.spec.*'
      - 'apps/crm/server/**/*.test.*'
      - 'apps/crm/server/**/*.spec.*'

  workflow_dispatch: {}

jobs:
  vitest-client-unit:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup PNPM
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          run_install: false

      - name: Setup Node 22.18.0
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24.18.0
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build shared package
        run: pnpm --filter @apps/crm-shared build

      - name: Build graphql codegen
        run: pnpm --filter @apps/crm-client codegen

      - name: Run client unit:tests
        run: pnpm --filter @apps/crm-client vitest:unit

  vitest-client-storybook:
    runs-on: ubuntu-latest
    environment: testing

    permissions:
      contents: read
      packages: read
      statuses: write

    container:
      # NOTE: playwright image version must match package.json playwright pkg
      image: mcr.microsoft.com/playwright:v1.60.0-noble

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup PNPM
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          run_install: false

      - name: Setup Node 22.18.0
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24.18.0
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: install dependencies
        run: pnpm install

      - name: build shared
        run: pnpm --filter @apps/crm-shared build

      - name: build graphql codegen
        run: pnpm --filter @apps/crm-client codegen

      - name: run Storybook tests
        run: pnpm --filter @apps/crm-client exec dotenvx run -f ./.env.ci.client.enc -- vitest run --mode test --config ./vitest.config.ts --project=storybook
        env:
          DOTENV_PRIVATE_KEY_CI_CLIENT: ${{ secrets.DOTENV_PRIVATE_KEY_CI_CLIENT }}

  vitest-server-unit:
    runs-on: ubuntu-latest
    environment: testing

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Recreate .env.test.server
        run: |
          printf "%s" "${{ secrets.ENV_TEST_SERVER_FILE }}" > apps/crm/server/.env.test.server
          chmod 600 apps/crm/server/.env.test.server

      - name: Setup PNPM
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          run_install: false

      - name: Setup Node 22.18.0
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24.18.0
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build shared package
        run: pnpm --filter @apps/crm-shared build

      - name: Build graphql codegen
        run: pnpm --filter @apps/crm-server codegen

      - name: Run server tests
        run: pnpm --filter @apps/crm-server vitest:test

      - name: Cleanup
        if: always()
        run: rm -f apps/crm/server/.env.test.server
