# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Vitest
permissions: read-all

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
    paths:
      - 'apps/crm/client/**/*.test.*'
      - 'apps/crm/client/**/*.spec.*'
      - 'apps/crm/server/**/*.test.*'
      - 'apps/crm/server/**/*.spec.*'

  push:
    branches: [main]
    paths:
      - 'apps/crm/client/**/*.test.*'
      - 'apps/crm/client/**/*.spec.*'
      - 'apps/crm/server/**/*.test.*'
      - 'apps/crm/server/**/*.spec.*'

  workflow_dispatch: {}

jobs:
  vitest-client:
    name: CRM Client Vitest
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PNPM
        uses: pnpm/action-setup@v5
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build shared package
        run: pnpm --filter @apps/crm-shared build

      - name: Build graphql codegen
        run: pnpm --filter @apps/crm-client codegen

      - name: Run client tests
        run: pnpm --filter @apps/crm-client vitest:unit

  vitest-server:
    name: CRM Server Vitest
    runs-on: ubuntu-latest
    environment: testing

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Recreate .env.test.server
        run: |
          printf "%s" "${{ secrets.ENV_TEST_SERVER_FILE }}" > apps/crm/server/.env.test.server
          chmod 600 apps/crm/server/.env.test.server

      - name: Setup PNPM
        uses: pnpm/action-setup@v5
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build shared package
        run: pnpm --filter @apps/crm-shared build

      - name: Build graphql codegen
        run: pnpm --filter @apps/crm-server codegen

      - name: Run server tests
        run: pnpm --filter @apps/crm-server vitest:test

      - name: Cleanup
        if: always()
        run: rm -f apps/crm/server/.env.test.server
